language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -U -r requirements_test.txt
  - pip install coveralls
script:
  - nosetests --cover-package=pymicrodb --tests=tests/ --with-coverage --cover-erase -v
after_success:
  coveralls
